# Generated by Django 4.2.13 on 2024-05-31 17:06

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('lesson_time', models.IntegerField(choices=[(0, '10:00'), (1, '11:00'), (2, '12:00'), (3, '14:00'), (4, '15:00'), (5, '16:00'), (6, '17:00')], default=0)),
                ('location', models.IntegerField(choices=[(0, 'Indoor'), (1, 'Outdoor')], default=0)),
                ('experience', models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advanced')], default=0)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_lesson.horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-lesson_date'],
            },
        ),
    ]
