# Generated by Django 4.2.13 on 2024-07-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_lesson', '0002_booking_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
