# Generated by Django 4.2.13 on 2024-05-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_lesson', '0003_alter_booking_options_horse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lesson_time',
            field=models.TimeField(choices=[(0, '10:00'), (1, '11:00'), (2, '12:00'), (3, '14:00'), (4, '15:00'), (5, '16:00'), (6, '17:00')], default=0),
        ),
    ]
