# Generated by Django 4.2.13 on 2024-07-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_lesson', '0003_booking_user_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='age',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_height',
        ),
    ]
