# Generated by Django 4.2.13 on 2024-07-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_lesson', '0004_remove_booking_age_remove_booking_user_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='age',
            field=models.IntegerField(blank=True, choices=[(0, 'Child'), (1, 'Adult')], default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
